# in _config.yml
title: "Foundations of Data Science with Python &mdash; Online Resources"
author: John M. Shea
copyright: "2021-2024"
only_build_toc_files: true
exclude_patterns : [ .virtual_documents/*]
logo: intro/normal-people.png
execute:
  execute_notebooks: "off"
parse:
  myst_enable_extensions: 
    - amsmath
    - html_image
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - linkify
    - smartquotes
sphinx:
  extra_extensions:
    - sphinx_sitemap
    - sphinxext.opengraph
    - sphinx.ext.imgconverter
    - notfound.extension
  config:
    project: "Foundations of Data Science with Python"
    #html_baseurl: "https://jmshea.github.io/Foundations-of-Data-Science-with-Python/"
    html_baseurl: "https://www.fdsp.net/"
    #mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    #mathjax_path: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML 
    #ogp_site_url: "https://jmshea.github.io/Foundations-of-Data-Science-with-Python/"
    ogp_site_url: "https://www.fdsp.net/"
    #ogp_image: "https://jmshea.github.io/Foundations-of-Data-Science-with-Python/_images/tools.png"
    ogp_image: "https://www.fdsp.net/images/3d-book.png"
    ogp_description_length: 200
    #mathjax3_config: { loader: {load: ['[tex]/action']}, tex: {packages: {'[+]': ['action']}}}
    image_converter_args: ["-density", "192"]
    mathjax3_config:
      loader: 
        load: ['[tex]/boldsymbol']
      tex:
        macros:
          "P" : "\\operatorname{P}"
        packages:
          '[+]': ['boldsymbol']
    notfound_context: {
                          'title': 'Page not found',
                          'body': '<h1><i>H<sub>0</sub></i> No &mdash; you failed to reject the null hypothesis!</h1><p><b></b></p><p>Unfortunately we could not find that content. You can use the magnifying glass to search or the table of contents to access specific pages<p><p><a href="intro.html">Return to the homepage</a></p><br><p>This website contains interactive activities and supporting materials for the book <i>Foundations of Data Science with Python</i> by John M. Shea:</p><a class="reference external image-reference" href="https://amzn.to/48PvKip"><img alt="Cover image for the published book Foundations of Data Science with Python by John M. Shea" class="align-center" src="_images/cover.jpeg" style="width: 200px;" /></a> <p>Purchase <i>Foundations of Data Science with Python</i> from <a class="reference external" href="https://amzn.to/48PvKip">Amazon</a><p>The scheduled publication date is February 22, 2024.</p><br><br><i>As an Amazon Associate I earn from qualifying purchases.</i>' 
                      }
    notfound_urls_prefix: "/fdsp/"
  #config:
    html_theme_options:
      repository_url: https://github.com/jmshea/Foundations-of-Data-Science-with-Python
      use_issues_button: true
      use_download_button: false
      use_repository_button: true
      use_edit_page_button: false
      home_page_in_toc: true
      analytics:
        google_analytics_id: G-51XGJJ29T3
