# in _config.yml
title: "Foundations of Data Science with Python"
author: John M. Shea
copyright: "2021-2023"
only_build_toc_files: true
logo: intro/normal-people.png
execute:
  execute_notebooks: "off"
parse:
  myst_enable_extensions: 
    - amsmath
    - html_image
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - linkify
    - smartquotes
sphinx:
  extra_extensions:
    - sphinx_sitemap
    - sphinxext.opengraph
    - sphinx.ext.imgconverter
  config:
    html_baseurl: "https://jmshea.github.io/Foundations-of-Data-Science-with-Python/"
    #mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    #mathjax_path: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML 
    ogp_site_url: "https://jmshea.github.io/Foundations-of-Data-Science-with-Python/"
    #ogp_image: "https://jmshea.github.io/Foundations-of-Data-Science-with-Python/_images/tools.png"
    ogp_image: "https://jmshea.github.io/Foundations-of-Data-Science-with-Python/_images/normal-people.png"
    ogp_description_length: 200
    #mathjax3_config: { loader: {load: ['[tex]/action']}, tex: {packages: {'[+]': ['action']}}}
    image_converter_args: ["-density", "192"]
    mathjax3_config:
      loader: 
        load: ['[tex]/boldsymbol']
      tex:
        macros:
          "P" : "\\operatorname{P}"
        packages:
          '[+]': ['boldsymbol']


html:
  base_url: https://jmshea.github.io/Foundations-of-Data-Science-with-Python/
  google_analytics_id: G-51XGJJ29T3
